### ISSUE TITLE
Use native lifetime value Drip field

### ISSUE THREAD

**Issue by pderksen** [davidhme/edd-drip#2]
Looks like this is in beta with the Drip API, but it would be nice to see lifetime value get stored in the Drip native field instead of the custom field.

https://www.getdrip.com/docs/rest-api#purchases

As a starting point, it looks like it's a calculated field taking from a purchase amount value.

**Comment by davidhme** [comment]
Didn't even realize Drip added a LTV field.

The drawback of dropping the custom field we've been using is that it would break backwards compatibility. Eg. I have my LTV stored in the custom field, and if we make this change all my values will end up being incorrect.

On the flipside it would be a good thing for new users.

Thoughts?

**Comment by pderksen** [comment]
@davidhme Not sure here. Maybe store in both for a while?

Possibly an additional checkbox setting under Downloads > Extensions > Drip Settings to store LTV as a custom field (checked by default to legacy users, but not checked for new installs)?

**Comment by derrickreimer** [comment]
The native LTV field is part of a "work in progress" effort with our purchases API. Anytime a purchase is recorded, the native LTV field gets auto-incremented. 

I would hold off using it for now in the plugin, though. The REST API for it is in beta (may change before it's finalized), and we have some work left to do to fully integrate purchases data into Drip. We have pretty big plans for the purchases API and will definitely keep you in the loop on new developments. We can iron out details like a migration path for converting `lifetime_value` custom field to the native LTV field. When it's ready for primetime, it would be great to get plugins like yours migrated to it. :+1:

**Comment by davidhme** [comment]
@djreimer Thanks, sounds good! We'll revisit it later.

**Comment by fpcorso** [comment]
Hey @davidhme! You mentioned a couple of years ago on this issue that you'll revisit the built-in LTV field for this plugin. Any thoughts on it? I use the built-in LTV field with other purchases for my email subscribers so I need to use it for EDD as well so cannot use a custom field.
