### ISSUE TITLE
price_name is no longer getting recorded since 1.4

### ISSUE THREAD

**Issue by davidhme** [davidhme/edd-drip#6]
From @pderksen:
"Update: Since 1.4 it looks like `price_name` is no longer getting recorded even to the purchase, yet quantity is now.

![image](https://cloud.githubusercontent.com/assets/79667/11603561/757c5e6e-9a97-11e5-94c6-4d9d6d5ff95f.png)
"

I can replicate the issue.

**Comment by davidhme** [comment]
Should have been fixed in 1.4.1

**Comment by pderksen** [comment]
@davidhme Thanks!
